# Generated by Django 5.2.3 on 2025-07-07 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investortype',
            options={'ordering': ['name'], 'verbose_name': 'Investor Type', 'verbose_name_plural': 'Investor Types'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='investor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='registry.investortype', verbose_name='Investor Type'),
        ),
    ]
