# Generated by Django 5.2.3 on 2025-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='operation_status',
            field=models.CharField(choices=[('active', 'Active / Operating'), ('inactive', 'Inactive / Dormant'), ('closed', 'Discontinued / Closed'), ('unknown', 'Unknown / Not Assessed')], default='active', help_text='Is the startup currently active or not?', max_length=50, verbose_name='Operation status'),
        ),
    ]
