# Generated by Django 5.2.3 on 2025-06-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('pre_seed', 'Pre-Seed Stage'), ('seed', 'Seed Stage'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c_plus', 'Series C and Beyond'), ('exit', 'IPO / Acquisition (Exit)')], default='pre_seed', max_length=20, verbose_name='Stage'),
        ),
    ]
