# Generated by Django 5.2.3 on 2025-07-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_investortype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization Type Name')),
            ],
            options={
                'verbose_name': 'Organization Type',
                'verbose_name_plural': 'Organization Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='investor_type',
        ),
        migrations.AlterField(
            model_name='organizationaffiliation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Affiliation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='registry.organizationtype', verbose_name='Organization Type'),
        ),
        migrations.DeleteModel(
            name='InvestorType',
        ),
    ]
