# Generated by Django 5.2.3 on 2025-06-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_startup_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='stage',
            field=models.CharField(choices=[('ideation', 'Ideation'), ('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c_plus', 'Series C and Beyond'), ('exit', 'IPO / Acquisition (Exit)')], default='pre_seed', max_length=20, verbose_name='Stage'),
        ),
    ]
