# Generated by Django 5.2.3 on 2025-07-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_organizationtype_remove_organization_investor_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Stage Name')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Development Stage',
                'verbose_name_plural': 'Development Stage',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='investmentstage',
            options={'ordering': ['created_at'], 'verbose_name': 'Funding Stage', 'verbose_name_plural': 'Funding Stage'},
        ),
        migrations.AddField(
            model_name='startup',
            name='funding_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='registry.investmentstage', verbose_name='Funding Stage'),
        ),
        migrations.AddField(
            model_name='startup',
            name='development_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='registry.developmentstage', verbose_name='Development Stage'),
        ),
    ]
