# Generated by Django 5.2.3 on 2025-06-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_startup_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Stage Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Startup Stage',
                'verbose_name_plural': 'Startup Stage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='startup',
            name='stage',
        ),
        migrations.AddField(
            model_name='startup',
            name='dev_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startups', to='registry.startupstage', verbose_name='Stage'),
        ),
    ]
