# Generated by Django 5.2.3 on 2025-06-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_startupstage_remove_startup_stage_startup_dev_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupstage',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description'),
        ),
    ]
