# Generated by Django 5.2.3 on 2025-06-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_startupstage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.CharField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('funds', models.DecimalField(blank=True, decimal_places=0, help_text='Total funds available for investment in USD', max_digits=15, null=True, verbose_name='Funds Available')),
                ('type', models.CharField(choices=[('angel', 'Angel Investor'), ('vc', 'VC Fund'), ('fof', 'VC Fund of Funds'), ('crowdfunding', 'Crowdfunding Platform'), ('accelerator', 'Accelerator/Incubator'), ('corporate', 'Corporate Investor'), ('family_office', 'Family Office'), ('government', 'Government Agency'), ('bank', 'Bank/Financial Institution'), ('pe_fund', 'Private Equity Fund'), ('other', 'Other')], default='other', max_length=50, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='startupstage',
            options={'ordering': ['created_at'], 'verbose_name': 'Startup Stage', 'verbose_name_plural': 'Startup Stage'},
        ),
    ]
