# Generated by Django 5.2.3 on 2025-06-28 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_investor_alter_startupstage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Investment Amount')),
                ('details', models.TextField(blank=True, help_text='Additional details about the investment', null=True, verbose_name='Details')),
                ('date', models.DateField(verbose_name='Investment Date')),
                ('type', models.CharField(choices=[('acquisition', 'Acquisition'), ('equity', 'Equity'), ('debt', 'Debt'), ('convertible_note', 'Convertible Note'), ('grant', 'Grant'), ('other', 'Other')], default='equity', max_length=50, verbose_name='Investment Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='registry.investor', verbose_name='Investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='registry.startup', verbose_name='Startup')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['date'],
            },
        ),
    ]
