# Generated by Django 5.2.3 on 2025-06-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='ownership',
            field=models.CharField(choices=[('private', 'Private'), ('government', 'Government'), ('government_affiliated', 'Government Affiliated'), ('other', 'Other')], default='government', help_text='Type of ownership or investment structure', max_length=50, verbose_name='Ownership Type'),
        ),
    ]
