# Generated by Django 5.2.3 on 2025-06-29 06:08

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_investor_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='startup',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='type',
            field=models.CharField(choices=[('angel', 'Angel Investor'), ('vc', 'VC Fund'), ('fof', 'VC Fund of Funds'), ('crowdfunding', 'Crowdfunding Platform'), ('accelerator', 'Accelerator/Incubator'), ('corporate', 'Corporate'), ('family_office', 'Family Office'), ('government', 'Government Agency'), ('bank', 'Bank/Financial Institution'), ('pe_fund', 'Private Equity Fund'), ('other', 'Other')], default='other', max_length=50, verbose_name='Type'),
        ),
    ]
