# Generated by Django 5.2.3 on 2025-06-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_startup_country_startup_region_alter_investor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(help_text='Target audience for the startup', max_length=100, verbose_name='Audience')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Target Audience',
                'verbose_name_plural': 'Target Audiences',
                'ordering': ['audience'],
            },
        ),
        migrations.AddField(
            model_name='startup',
            name='business_model',
            field=models.CharField(blank=True, help_text='Brief description of the business model', max_length=100, null=True, verbose_name='Business Model'),
        ),
        migrations.AddField(
            model_name='startup',
            name='target_audience',
            field=models.ManyToManyField(blank=True, help_text='Target audience for the startup', null=True, related_name='startups', to='registry.targetaudience', verbose_name='Target Audience'),
        ),
    ]
