# Generated by Django 5.2.3 on 2025-06-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_targetaudience_startup_business_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='business_model',
        ),
    ]
