# Generated by Django 5.2.3 on 2025-06-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_remove_startup_business_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type Name')),
            ],
            options={
                'verbose_name': 'Investor Type',
                'verbose_name_plural': 'Investor Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='investor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='registry.investortype', verbose_name='Type'),
        ),
    ]
