# Generated by Django 5.2.3 on 2025-06-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_investortype_alter_investor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='type',
            new_name='investor_type',
        ),
    ]
