# Generated by Django 5.2.3 on 2025-06-29 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_rename_type_investor_investor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='investor_type',
        ),
    ]
