# Generated by Django 5.2.3 on 2025-06-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_remove_investor_investor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='target_audience',
            field=models.ManyToManyField(blank=True, help_text='Target audience for the startup', related_name='startups', to='registry.targetaudience', verbose_name='Target Audience'),
        ),
    ]
