# Generated by Django 5.2.3 on 2025-06-29 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_alter_startup_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investor_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='registry.investortype', verbose_name='Type'),
        ),
    ]
