# Generated by Django 5.2.3 on 2025-06-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_investor_investor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type Name')),
            ],
            options={
                'verbose_name': 'Investor Type',
                'verbose_name_plural': 'Investor Types',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='investor',
            old_name='funds',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='ownership',
        ),
        migrations.AddField(
            model_name='investor',
            name='affilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investors', to='registry.investoraffiliation', verbose_name='Affiliation'),
        ),
    ]
