# Generated by Django 5.2.3 on 2025-06-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_investoraffiliation_rename_funds_investor_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='affilation',
            new_name='affiliation',
        ),
    ]
