# Generated by Django 5.2.3 on 2025-06-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_rename_affilation_investor_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='apply_link',
            field=models.CharField(blank=True, help_text='Link to apply for investment or partnership', null=True, verbose_name='Application Link'),
        ),
    ]
