# Generated by Django 5.2.3 on 2025-06-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_investor_apply_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartupStage',
            new_name='InvestmentStage',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='dev_stage',
        ),
        migrations.AddField(
            model_name='investment',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='registry.investmentstage', verbose_name='Investment Stage'),
        ),
    ]
