# Generated by Django 5.2.3 on 2025-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_rename_startupstage_investmentstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the deal', null=True, verbose_name='Investment Date'),
        ),
    ]
