# Generated by Django 5.2.3 on 2025-06-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_alter_investment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Investment Type')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Investment Type',
                'verbose_name_plural': 'Investment Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='investment',
            name='type',
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='registry.investmenttype', verbose_name='Investment Type'),
        ),
    ]
