# Generated by Django 5.2.3 on 2025-06-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_investmenttype_remove_investment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='investment_type',
        ),
        migrations.DeleteModel(
            name='InvestmentType',
        ),
    ]
