# Generated by Django 5.2.3 on 2025-06-29 15:08

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_remove_investment_investment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.CharField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', help_text='Mode of operation for the incubator', max_length=50, verbose_name='Mode')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('duration', models.CharField(blank=True, help_text='Duration of the program (e.g., 6 months, 1 year)', max_length=100, null=True, verbose_name='Duration')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of startups that can be supported at a time', null=True, verbose_name='Capacity')),
                ('fee_structure', models.TextField(blank=True, help_text='Details about the fee structure for the program (if any)', null=True, verbose_name='Fee Structure')),
                ('apply_link', models.CharField(blank=True, help_text='Link to apply for the incubator program', null=True, verbose_name='Application Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', help_text='Current status of the incubator program', max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Incubator',
                'verbose_name_plural': 'Incubators',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupportProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Support Program Type',
                'verbose_name_plural': 'Support Program Types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='investoraffiliation',
            options={'ordering': ['name'], 'verbose_name': 'Investor Affiliation', 'verbose_name_plural': 'Investor Affiliations'},
        ),
        migrations.CreateModel(
            name='SupportProgramCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Cycle Name')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the program cycle', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('participating_startups', models.ManyToManyField(blank=True, help_text='Startups participating in this program cycle', related_name='program_cycles', to='registry.startup', verbose_name='Participating Startups')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='registry.supportprogram', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Support Program Cycle',
                'verbose_name_plural': 'Support Program Cycles',
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='supportprogram',
            name='program_type',
            field=models.ForeignKey(blank=True, help_text='Type of support program', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='registry.supportprogramtype', verbose_name='Program Type'),
        ),
    ]
