# Generated by Django 5.2.3 on 2025-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0025_alter_supportprogram_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportprogram',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='supportprogram',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='supportprogram',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='supportprogram',
            name='fee_structure',
        ),
        migrations.AddField(
            model_name='supportprogramcycle',
            name='application_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('will be announced', 'Will be announced')], default='open', help_text='Current application status for the program cycle', max_length=50, verbose_name='Application Status'),
        ),
        migrations.AddField(
            model_name='supportprogramcycle',
            name='apply_link',
            field=models.CharField(blank=True, help_text='Link to apply for the incubator program', null=True, verbose_name='Application Link'),
        ),
        migrations.AddField(
            model_name='supportprogramcycle',
            name='capacity',
            field=models.CharField(blank=True, help_text='Maximum number of startups that can be supported at a time', null=True, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='supportprogramcycle',
            name='duration',
            field=models.CharField(blank=True, help_text='Duration of the program (e.g., 6 months, 1 year)', max_length=100, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='supportprogramcycle',
            name='fee_structure',
            field=models.TextField(blank=True, help_text='Details about the fee structure for the program (if any)', null=True, verbose_name='Fee Structure'),
        ),
    ]
