# Generated by Django 5.2.3 on 2025-06-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0026_remove_supportprogram_apply_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('website', models.CharField(blank=True, null=True, verbose_name='Website')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Support Organization',
                'verbose_name_plural': 'Support Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='supportprogram',
            name='address',
        ),
        migrations.AddField(
            model_name='supportprogramcycle',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='supportprogram',
            name='managing_organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations managing the incubator program', related_name='programs', to='registry.supportorganizations', verbose_name='Managing Organizations'),
        ),
    ]
