# Generated by Django 5.2.3 on 2025-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('email', models.CharField(help_text='Email', max_length=100)),
                ('message', models.TextField(help_text='Message', max_length=1000)),
            ],
        ),
    ]
