# Generated by Django 5.2.3 on 2026-03-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('email', models.CharField(blank=True, help_text='Email', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone', max_length=100, null=True)),
                ('startup_name', models.CharField(blank=True, help_text='Startup Name', max_length=100, null=True)),
                ('startup_pitchdeck', models.CharField(blank=True, help_text='Startup Pitchdeck', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['-id'],
            },
        ),
    ]
