# Generated by Django 5.2.3 on 2026-03-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_participant_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='region',
            field=models.CharField(choices=[('andijan', 'Andijan'), ('ferghana', 'Ferghana'), ('namangan', 'Namangan'), ('surkhandarya', 'Surkhandarya')], max_length=20, verbose_name='Region'),
        ),
    ]
