# Generated by Django 5.2.3 on 2026-03-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_alter_participant_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, help_text='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='region',
            field=models.CharField(blank=True, choices=[('andijan', 'Andijan'), ('ferghana', 'Ferghana'), ('namangan', 'Namangan'), ('surkhandarya', 'Surkhandarya')], max_length=20, null=True, verbose_name='Region'),
        ),
    ]
