# Generated by Django 5.2.3 on 2026-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_alter_participant_name_alter_participant_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='problem',
            field=models.TextField(blank=True, help_text='For whom and what is the problem?', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='solution',
            field=models.TextField(blank=True, help_text='Describe the solution your startup offers', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_description',
            field=models.TextField(blank=True, help_text='Startup Description', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='startup_stage',
            field=models.CharField(blank=True, choices=[('idea_prototype', 'Idea/Prototype'), ('mvp', 'MVP'), ('first_users', 'First Users'), ('revenue', 'Revenue'), ('breakeven_point', 'Breakeven Point')], help_text='Current stage of the startup', max_length=20, null=True, verbose_name='Startup Stage'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_description',
            field=models.TextField(blank=True, help_text='Describe your team', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='traction',
            field=models.TextField(blank=True, help_text='Briefly describe the traction your startup has achieved', null=True),
        ),
    ]
