# Generated by Django 5.2.3 on 2025-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctamessage',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
