# Generated by Django 5.2.3 on 2025-06-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_ctamessage_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctamessage',
            name='active',
        ),
        migrations.AddField(
            model_name='ctamessage',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Show CTA Message'),
        ),
        migrations.AddField(
            model_name='sitenotification',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Show Notification'),
        ),
    ]
